### PR TITLE
Add table prefix option and Ukrainian localization

### PR DESCRIPTION
**Pull request by GIGABAIT93**

### CODE REVIEW

**Comment by Elikill58** [comment]
Thanks for this PR! I'll check it and merge it quickly :)

**Comment by Elikill58** [comment]
I'm actually testing and the prefix variable doesn't seems to work (and there is a typo with the "history" table name). I'm checking for solution but If you find a fix, it's nice

**Comment by GIGABAIT93** [comment]
does not work? It's strange for me everything works fine. So I accidentally changed the name in history class

**Comment by GIGABAIT93** [comment]
> I'm actually testing and the prefix variable doesn't seems to work (and there is a typo with the "history" table name). I'm checking for solution but If you find a fix, it's nice

can you tell me what exactly is not working or where you are getting the error?

**Comment by Elikill58** [comment]
> > I'm actually testing and the prefix variable doesn't seems to work (and there is a typo with the "history" table name). I'm checking for solution but If you find a fix, it's nice
> 
> can you tell me what exactly is not working or where you are getting the error?

I just fixed it. The problem was that the prefix were not added to "history" object. I made a trick and now it's fine

**Comment by GIGABAIT93** [comment]
Nice

**Comment by Elikill58** [comment]
> Nice

Yes, thanks again for your PR! I'll make an update

**Pull request merged**
